version: '1'

services:
  user-service:
    platform: 'linux/amd64'
    image: 'product-service:latest'
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - product-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8181
    expose:
      - "8181"
    ports:
      - "8181:8181"
  product-db:
    image: 'postgres:15-alpine'
    container_name: product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - product-db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
volumes:
  product-db:
